package io.nirahtech.erp.bank;

public enum BankAccountType {
    COMPANY_ACCOUNT,
    STUDENT_BANK_ACCOUNT,
    INDIVIDUAL_RETIREMENT_ACCOUNT,
    DEPOSIT_CERTIFICATE_ACOUNT,
    MONEY_MARKER_ACCOUNT,
    SAVINGS_ACCOUNT,
    CURRENT_ACCOUNT;
}
